name: Front Image CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

permissions:
  contents: write

env:
  IMAGE_TAG: dev-1

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: QEMU 설정
        uses: docker/setup-qemu-action@v1

      - name: Docker Buildx 설정
        uses: docker/setup-buildx-action@v1

      - name: DockerHub에 로그인
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 빌드 및 푸쉬
        uses: docker/build-push-action@v2
        with:
          context: .  # Next.js 프로젝트 디렉토리 경로로 변경
          file: ./Dockerfile  # Dockerfile 경로로 변경
          push: true
          tags: 7eom14/tubeplus:${{ env.IMAGE_TAG }}  # DockerHub의 사용자 이름 및 저장소 이름으로 변경
          platforms: linux/amd64
